### PR TITLE
Add separate intent for setting the volume to a percentage

### PR DESCRIPTION
**Pull request by visadb**
This fixes issue #80.

### CODE REVIEW

**Comment by visadb** [comment]
I'll write tests for the new intent.

**Comment by thorpelawrence** [comment]
Looks good to me! Were you able to test this manually by any chance?

**Comment by visadb** [comment]
> Looks good to me! Were you able to test this manually by any chance?

Nope, I'm new to Alexa skill development and didn't want to expend the time and energy to setup things for manual testing. And it's hopefully too simple a change to botch. 😅

**Comment by thorpelawrence** [comment]
No problem, I will merge it and submit to Amazon, which might take a few days for approval

Thanks!

**Review by thorpelawrence — APPROVED** [review]

**Comment by thorpelawrence** [comment]
Hi @visadb

Amazon have accepted the changes so it should be live now, thanks again

**Pull request merged**
