### PR TITLE
pt-br locale added

### PR DESCRIPTION
**Pull request by diegom4riano**
pt-br locale added so now we can talk to spotify  and bose in portuguese

### CODE REVIEW

**Comment by thorpelawrence** [comment]
Hi there

I will submit the new language to amazon for it to be added to the skill on their store, hopefully it will be approved within a few weeks (sometimes they take a long time to approve it)

Thanks for your contribution!

**Comment by thorpelawrence** [comment]
One other thing before I can submit, is could you please fill out the details listed here for the local store page listing?

https://github.com/thorpelawrence/alexa-spotify-connect/issues/14#issuecomment-365770234

Thanks

**Comment by diegom4riano** [comment]
Hi, sure!

Name: Connect Control para Spotify
Invocation Name can stay the same

Description:
Utilize o Spotify Connect para Alexa em português.

Source code: https://github.com/thorpelawrence/alexa-spotify-connect

O uso em alguns dispositivos pode exigir uma conta Spotify Premium

IMPORTANTE:
Este produto não é endossado, certificado ou aprovado pelo Spotify. Spotify é uma marca registrada do Spotify Group.

Samples phrases:

Alexa
        "reproduzir música"
        "toque um pouco de música"
        "quero escutar um pouco de música"

**Comment by thorpelawrence** [comment]
Thanks again, I've submitted it to Amazon, just need to wait for their approval which may take a couple of weeks

**Pull request merged**
