### PR TITLE
Spanish Localization

### PR DESCRIPTION
**Pull request by mediocaballero**
Added texts and id for es-ES locale

### CODE REVIEW

**Comment by gonzadk** [comment]
should this be working properly? I am not able to have it working on Spanish.. I tried in English and it's working fine but there is no response when I try in Spanish

**Comment by gonzadk** [comment]
well.. I figured out which was the problem with it, these translations where made only for Spanish (Spain) and I am using Spanish (Mexico)..
I will create a new PR with the proper translations, probably tomorrow :)

**Comment by mediocaballero** [comment]
Hi @thorpelawrence!

I almost missed this as the message popped up on mobile while on holidays :-)

I've created https://github.com/thorpelawrence/alexa-spotify-connect/pull/73 to update the translations, but I'm not sure if something else needs to be added to the utterances file :-m

**Comment by thorpelawrence** [comment]
> Hi @thorpelawrence!
> 
> I almost missed this as the message popped up on mobile while on holidays :-)
> 
> I've created #73 to update the translations, but I'm not sure if something else needs to be added to the utterances file :-m

Thanks for updating! I've just merged it.

As for utterances I cannot remember so no problem if not, but I think it would be similar to the changes in `de-DE.json`

**Pull request merged**
